[theme]
# светлая тема

primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"


# темная тема

#primaryColor="#d33682"
#backgroundColor="#002b36"
#secondaryBackgroundColor="#586e75"
#textColor="#fafafa"
#font="sans serif"

